
services:
  php:
    image: php:8.1-apache
    container_name: php_app
    ports:
      - "8080:80" # Expose the application on localhost:8080
    volumes:
      - ./app:/var/www/html # Mount your application code
      - ./app/main.db:/var/www/html/main.db # Mount SQLite database
    restart: always
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html